
@startuml

title Regularization Voucher App
actor User
entity Frontend
entity Keycloak #red
entity Backend #orange
entity Sylob #green
database Base

' AUTHENTICATION PROCESS

User -> Frontend:  Type user name and password
Frontend -> Keycloak: Authentication Request
Keycloak -> Keycloak: Log transaction
Keycloak -> User: Authentication Response
Keycloak -> Backend: Give an access to user

'VIEW AVAILABLE KITS

User -> Frontend: Consult available kits
Frontend -> Backend: Sends the request
Backend -> Sylob: Executes the request (through the Proxy)
Sylob -> Backend: Sends Kits for the user hospital
Backend -> Frontend: Sends data
Frontend -> Frontend: Displays kits for user

'VIEW A SPECIFIC KIT CONTENT

User -> Frontend: Consults a specific kit content
Frontend -> Backend: Sends the request
Backend -> Sylob: Executes request (through the Proxy)
Sylob -> Backend: Sends articles for the selected kit
Backend -> Frontend: Sends data
Frontend -> Frontend: Displays the result

' MAKING A REGULARIZATION VOUCHER

User -> Frontend: Selects one or several articles
Backend -> Base: Save voucher (Articles, not the pdf file)
Frontend -> Backend: Make a pdf file with selected articles
Backend -> Backend: Sends email with the pdf file
@enduml